title: September 2018, Publishing web maps and processing spatial data with modern JavaScript
email: rgaston@fargeo.com
description:
baseurl: ""
github_username:  rgaston

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
